// AI 快速入口数据 —— 手工维护，独立于 links.js（build_nav_data.py 不会覆盖本文件）。
// links.js 是"研究信源"目录；本文件是"打开即用"的工具/控制台启动器，两者职责不同。
window.NAV_AI = {
  "updated": "2026-06-12",
  "tools": [
    {"name":"DeepSeek","url":"https://chat.deepseek.com/","domain":"chat.deepseek.com","desc":"中文分析、推理和低成本研究辅助。"},
    {"name":"ChatGPT","url":"https://chatgpt.com/","domain":"chatgpt.com","desc":"通用问答、分析、写作与代码协作。"},
    {"name":"Claude","url":"https://claude.ai/","domain":"claude.ai","desc":"长文阅读、分析、写作和结构化推理。"},
    {"name":"Gemini","url":"https://gemini.google.com/","domain":"gemini.google.com","desc":"Google 生态下的多模态 AI 助手。"},
    {"name":"Perplexity","url":"https://www.perplexity.ai/","domain":"perplexity.ai","desc":"带引用的快速搜索与问题探索。"},
    {"name":"Grok","url":"https://grok.com/","domain":"grok.com","desc":"实时语境、社交话题与快速问答。"},
    {"name":"Copilot","url":"https://copilot.microsoft.com/","domain":"copilot.microsoft.com","desc":"Microsoft AI 助手。"},
    {"name":"Meta AI","url":"https://www.meta.ai/","domain":"meta.ai","desc":"Meta AI 助手。"},
    {"name":"Le Chat","url":"https://chat.mistral.ai/","domain":"chat.mistral.ai","desc":"Mistral 官方聊天入口。"},
    {"name":"Poe","url":"https://poe.com/","domain":"poe.com","desc":"多模型入口，用于横向比较不同 AI。"},
    {"name":"You.com","url":"https://you.com/","domain":"you.com","desc":"AI 搜索和助手。"},
    {"name":"Kimi","url":"https://kimi.moonshot.cn/","domain":"kimi.moonshot.cn","desc":"中文长文档、资料阅读和信息整理。"},
    {"name":"通义千问","url":"https://tongyi.aliyun.com/qianwen/","domain":"tongyi.aliyun.com","desc":"阿里通义千问。"},
    {"name":"豆包","url":"https://www.doubao.com/","domain":"doubao.com","desc":"字节跳动 AI 助手。"},
    {"name":"文小言","url":"https://yiyan.baidu.com/","domain":"yiyan.baidu.com","desc":"百度文心一言 / 文小言。"},
    {"name":"智谱清言","url":"https://chatglm.cn/","domain":"chatglm.cn","desc":"智谱 AI 助手。"},
    {"name":"讯飞星火","url":"https://xinghuo.xfyun.cn/","domain":"xinghuo.xfyun.cn","desc":"科大讯飞星火大模型。"},
    {"name":"腾讯元宝","url":"https://yuanbao.tencent.com/","domain":"yuanbao.tencent.com","desc":"腾讯混元 AI 助手。"},
    {"name":"海螺AI","url":"https://hailuoai.com/","domain":"hailuoai.com","desc":"MiniMax 海螺 AI。"},
    {"name":"阶跃星辰","url":"https://yuewen.cn/","domain":"yuewen.cn","desc":"阶跃星辰 AI 助手。"},
    {"name":"秘塔AI","url":"https://metaso.cn/","domain":"metaso.cn","desc":"AI 搜索与信息整理。"},
    {"name":"纳米AI","url":"https://www.n.cn/","domain":"n.cn","desc":"360 纳米 AI 搜索。"},
    {"name":"Midjourney","url":"https://www.midjourney.com/","domain":"midjourney.com","desc":"AI 图像生成。"},
    {"name":"Runway","url":"https://runwayml.com/","domain":"runwayml.com","desc":"AI 视频生成。"},
    {"name":"可灵AI","url":"https://klingai.kuaishou.com/","domain":"klingai.kuaishou.com","desc":"可灵视频生成。"},
    {"name":"即梦AI","url":"https://jimeng.jianying.com/","domain":"jimeng.jianying.com","desc":"图像和视频创作。"},
    {"name":"Suno","url":"https://suno.com/","domain":"suno.com","desc":"AI 音乐生成。"},
    {"name":"ElevenLabs","url":"https://elevenlabs.io/","domain":"elevenlabs.io","desc":"AI 语音生成。"}
  ],
  "api": [
    {"name":"DeepSeek API","url":"https://platform.deepseek.com/","domain":"platform.deepseek.com","desc":"DeepSeek API 平台。"},
    {"name":"OpenAI API","url":"https://platform.openai.com/","domain":"platform.openai.com","desc":"OpenAI API 控制台。"},
    {"name":"Claude API","url":"https://platform.claude.com/","domain":"platform.claude.com","desc":"Claude API 控制台。"},
    {"name":"Google AI Studio","url":"https://aistudio.google.com/","domain":"aistudio.google.com","desc":"Gemini API 与模型实验。"},
    {"name":"Mistral Console","url":"https://console.mistral.ai/","domain":"console.mistral.ai","desc":"Mistral API 控制台。"},
    {"name":"xAI Console","url":"https://console.x.ai/","domain":"console.x.ai","desc":"Grok / xAI API 控制台。"},
    {"name":"OpenRouter","url":"https://openrouter.ai/","domain":"openrouter.ai","desc":"多模型 API 路由。"},
    {"name":"Together AI","url":"https://www.together.ai/","domain":"together.ai","desc":"开源模型 API 与推理服务。"},
    {"name":"Replicate","url":"https://replicate.com/","domain":"replicate.com","desc":"模型托管与调用。"},
    {"name":"Hugging Face","url":"https://huggingface.co/","domain":"huggingface.co","desc":"模型、数据集与推理入口。"},
    {"name":"SiliconFlow","url":"https://cloud.siliconflow.cn/","domain":"cloud.siliconflow.cn","desc":"硅基流动模型 API 平台。"},
    {"name":"阿里云百炼","url":"https://bailian.console.aliyun.com/","domain":"bailian.console.aliyun.com","desc":"通义千问与阿里模型 API。"},
    {"name":"火山方舟","url":"https://console.volcengine.com/ark/","domain":"console.volcengine.com","desc":"豆包与火山模型服务。"},
    {"name":"百度千帆","url":"https://console.bce.baidu.com/qianfan/","domain":"console.bce.baidu.com","desc":"百度千帆大模型平台。"},
    {"name":"腾讯混元","url":"https://console.cloud.tencent.com/hunyuan/","domain":"console.cloud.tencent.com","desc":"腾讯混元 API。"},
    {"name":"智谱开放平台","url":"https://open.bigmodel.cn/","domain":"open.bigmodel.cn","desc":"智谱 GLM API。"},
    {"name":"月之暗面","url":"https://platform.moonshot.cn/","domain":"platform.moonshot.cn","desc":"Kimi / Moonshot API。"},
    {"name":"MiniMax 开放平台","url":"https://platform.minimaxi.com/","domain":"platform.minimaxi.com","desc":"MiniMax API。"},
    {"name":"阶跃开放平台","url":"https://platform.stepfun.com/","domain":"platform.stepfun.com","desc":"阶跃星辰 API。"},
    {"name":"讯飞开放平台","url":"https://www.xfyun.cn/","domain":"xfyun.cn","desc":"讯飞星火 API。"},
    {"name":"302.AI","url":"https://302.ai/","domain":"302.ai","desc":"AI 应用与 API 聚合入口。"},
    {"name":"AiHubMix","url":"https://aihubmix.com/","domain":"aihubmix.com","desc":"多模型 API 聚合入口。"},
    {"name":"DMXAPI","url":"https://www.dmxapi.com/","domain":"dmxapi.com","desc":"多模型 API 中转入口。"},
    {"name":"OhMyGPT","url":"https://www.ohmygpt.com/","domain":"ohmygpt.com","desc":"多模型 API 中转入口。"}
  ]
};
